name: counterfeit_detector
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  flutter_native_splash: ^2.3.2
  persistent_bottom_nav_bar: ^5.0.2
  http: ^0.13.3  # Agrega la versión que desees usar


 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
  - assets/

