name: counterfeit_detector
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  camera: ^0.10.5+3
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  percent_indicator: ^4.2.3
  flutter_native_splash: ^2.3.2
  persistent_bottom_nav_bar: ^5.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  http: ^0.13.3
  firebase_storage: ^11.2.6
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  
  assets:
  - assets/
  
